import 'level_template.dart';

const levelTemplates = [
  LevelTemplate(
    templateId: 1,
    baseTargetScore: 1000,
    baseMoves: 25,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 5,
  ),
  LevelTemplate(
    templateId: 2,
    baseTargetScore: 1200,
    baseMoves: 24,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 5,
  ),
  LevelTemplate(
    templateId: 3,
    baseTargetScore: 1400,
    baseMoves: 23,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 5,
  ),
  LevelTemplate(
    templateId: 4,
    baseTargetScore: 1600,
    baseMoves: 22,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 6,
  ),
  LevelTemplate(
    templateId: 5,
    baseTargetScore: 1800,
    baseMoves: 22,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 6,
  ),
  LevelTemplate(
    templateId: 6,
    baseTargetScore: 2000,
    baseMoves: 21,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 6,
  ),
  LevelTemplate(
    templateId: 7,
    baseTargetScore: 2200,
    baseMoves: 21,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 6,
  ),
  LevelTemplate(
    templateId: 8,
    baseTargetScore: 2400,
    baseMoves: 20,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 6,
  ),
  LevelTemplate(
    templateId: 9,
    baseTargetScore: 2600,
    baseMoves: 20,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 6,
  ),
  LevelTemplate(
    templateId: 10,
    baseTargetScore: 2800,
    baseMoves: 20,
    boardRows: 8,
    boardColumns: 8,
    baseTileVariantCount: 6,
  ),
];
